### ISSUE TITLE
feature request: format git-hunks only

### ISSUE THREAD

**Issue by becknik** [stevearc/conform.nvim#371] opened 2024-04-13 14:22 UTC
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

It'd be really nice to have an option to just format the lines in the buffer which are indexed by git or aren't in stage yet.

I've thought about an additional property in the `opt` attribute of the `format_on_save` function, to just run the formatting on git hunks if enabled.

Certainly, this could be out of scope for this plugin.
But I'm not really sure how to implement this feature myself just using your API & Lua...

### Provide background

When working on projects a style guide wasn't established to a certain point, I'd be nice to gradually format the source code without loosing track of the file blames by reformatting the whole project code at once.

Also, I'd like to avoid covering the blame/hunks of my team comrades with my auto-formatting, when they disobey the style guide due to laziness/ by accident or whatever reason there is.

### What is the significance of this feature?

nice to have

**Comment by stevearc** [comment] 2024-04-20 00:51
Duplicate of #92. There's a workaround posted there, as well as some more context.

**Closed by stevearc** 2024-04-20 00:51 UTC
Labels: enhancement
