### ISSUE TITLE
bug: Formatter fails because Windows user path contains an space

### ISSUE THREAD

**Issue by TheRustifyer** [stevearc/conform.nvim#276] opened 2024-01-20 14:12 UTC
### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 11

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

Log file: C:\Users\Alex Vergara\AppData\Local\nvim-data\conform.log
          operable program or batch file.
          
          15:05:28[ERROR] Formatter 'stylua' error: 'C:\Users\Alex' is not recognized as an internal or external command,
          operable program or batch file.
          
          15:07:38[ERROR] Formatter 'stylua' error: 'C:\Users\Alex' is not recognized as an internal or external command,
          operable program or batch file.
          
          15:08:10[ERROR] Formatter 'stylua' error: 'C:\Users\Alex' is not recognized as an internal or external command,
          operable program or batch file.
          
          15:08:13[ERROR] Formatter 'stylua' error: 'C:\Users\Alex' is not recognized as an internal or external command,
          operable program or batch file.
          
          15:08:16[ERROR] Formatter 'stylua' error: 'C:\Users\Alex' is not recognized as an internal or external command,
          operable program or batch file.
          
          15:08:17[ERROR] Formatter 'stylua' error: 'C:\Users\Alex' is not recognized as an internal or external command,
          operable program or batch file.

### Describe the bug

`Conform` just fails to work because in some on my Windows machines, I have a username with an space in it, so it isn't recovering the full path to the formatter.

### What is the severity of this bug?

blocking (cannot use plugin)

### Steps To Reproduce

1. Format on save

### Expected Behavior

The file gets correctly formatted

### Additional context

I am using the starter template of `LazyVim` with most of it's default configuration yet,

**Comment by stevearc** [comment] 2024-01-21 00:55
duplicate of #252

**Closed by stevearc** 2024-01-21 00:55 UTC
Labels: bug
