### ISSUE TITLE
Feature suggestion: Define LSP formatting in `formatters_by_ft`

### ISSUE THREAD

**Issue by chrisgrieser** [stevearc/conform.nvim#129] opened 2023-10-10 15:40 UTC
Right now, CLI formatters are listed in `formatters_by_ft`, and LSP formatting is defined via `lsp_fallback`, which can be set in the config or in the keymap. When you want to use LSP formatting for some filetypes, and formatting via CLI for other filetypes, the config for that is pretty much split up into several places and one also has to pay attention to the distinction between `lsp_fallback = "always"` and `lsp_fallback = true`.

My suggestion is to list `lsp` in the `formatters_by_ft` table, which simplifies the formatting setup. Everything would be located in one place, and fallback-behavior would be defined the same way as with CLI formatters, making `conform.nvim`'s more consistent.

```lua
require("conform").setup {
	formatters_by_ft = {
		-- run only CLI
		html = { "prettier" },

		-- run only LSP
		toml = { "lsp" },

		-- always run LSP after stylelint (like `lsp_fallback = "always"`)
		css = { "stylelint", "lsp" }, 

		-- sublist, run LSP only when stylua not available (like `lsp_fallback = true`)
		lua = { { "stylua", "lsp" } }, 
	},
}
```

**Comment by stevearc** [comment] 2023-10-10 16:06
Dupe of #61.

Agree the API is nice, but the amount of hacks required to build that API is not worth it.

**Closed by stevearc** 2023-10-10 16:06 UTC

**Comment by chrisgrieser** [comment] 2023-10-11 09:36
I see. In that case, how about this, then? I feel like this way, we can at least keep all the config in one place, instead of having things like `require("conform").format { lsp_fallback = "always" }` defined for specific filetypes only.

```lua
require("conform").setup {
	formatters_by_ft = {
		html = { "prettier" },
		css = { "stylelint" }, 
		lua = { "stylua"  }, 
	},
	lsp_fallback = {
		html = { "always" },
		css = { true }, 
		lua = { false }, 
		["*"] = { true }, 
	},
}
```

**Comment by stevearc** [comment] 2023-10-11 15:12
This is something I'm trying to avoid. I don't want the config options and structure to grow to become increasingly complex. This behavior is quite easy to add on your own, and most people won't need it, so I think it makes sense to just add it in your own config

```lua
local lsp_fallback = setmetatable({
  html = "always",
  lua = false,
}, {
  -- default true
  __index = function() return true end,
})
require("conform").setup({
  formatters_by_ft = {
    html = { "prettier" },
    css = { "stylelint" },
    lua = { "stylua" },
  },
  format_on_save = function(buf)
    return {
      lsp_fallback = lsp_fallback[vim.bo[buf].filetype],
    }
  end,
})
```
