### ISSUE TITLE
bug: conditonally disabled formatters are re-activated

### ISSUE THREAD

**Issue by lgmys** [stevearc/conform.nvim#227] opened 2023-11-30 11:26 UTC
### Neovim version (nvim -v)

0.9.4

### Operating system/version

Linux 6.6.1 arch

### Add the debug logs

- [X] I have set `log_level = vim.log.levels.DEBUG` and pasted the log contents below.

### Log file

          12:15:21[DEBUG] Run CWD: /home/luke/projects/test/apps/test-web
          12:15:21[DEBUG] prettier exited with code 0
          12:15:48[DEBUG] Running formatters on /home/luke/projects/test/apps/test-web/src/product/gallery/GalleryComponent.tsx: {}
          12:15:48[DEBUG] Running LSP formatter on /home/luke/projects/test/apps/test-web/src/product/gallery/GalleryComponent.tsx
          12:16:07[DEBUG] Running formatters on /home/luke/projects/test/apps/test-web/src/product/gallery/GalleryComponent.tsx: { "prettier" }
          12:16:07[INFO] Run prettier on /home/luke/projects/test/apps/test-web/src/product/gallery/GalleryComponent.tsx
          12:16:07[DEBUG] Run command: { "/home/luke/projects/test/node_modules/.bin/prettier", "--stdin-filepath", "/home/luke/projects/test/apps/test-web/src/product/gallery/GalleryComponent.tsx" }
          12:16:07[DEBUG] Run CWD: /home/luke/projects/test/apps/test-web
          12:16:07[DEBUG] prettier exited with code 0

### Describe the bug

Thank you for this great plugin!

So, I have this condition that should disable prettier - and I can see that it works initially - after sample tsx file is open, I can see that `prettier` formatter is disabled and formatting correctly falls back to lsp.

Subsequent saves of the same document are still running prettier for me though.

Any ideas?

### Steps To Reproduce

1. load the sample init file
2. try saving the tsx file twice

### Expected Behavior

Condition should be respected at every formatter run - maybe I understand the notion of condition wrong?

### Minimal example file

Just about any `*.tsx` file

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/conform.nvim",
    config = function()
      require("conform").setup({
        log_level = vim.log.levels.DEBUG,
        		formatters_by_ft = {
			lua = { "stylua" },
			javascript = { "prettier" },
			typescript = { "prettier" },
			typescriptreact = { "prettier" },
			javascriptreact = { "prettier" },
		},
		formatters = {
			prettier = {
				condition = function(ctx)
					return false
				end,
			},
		},

      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by lgmys** [comment] 2023-11-30 12:11
solved my problem with custom autoformat logic but still, this should not happen I think:)

**Comment by stevearc** [comment] 2023-12-01 08:14
Using the minimal config and a typescript file, I cannot reproduce the issue. What is the output of `:ConformInfo`?

**Comment by lgmys** [comment] 2023-12-01 10:36
That would be:
```
Formatters for this buffer:
LSP: eslint
prettier ready (javascriptreact, typescriptreact, typescript, javascript)

Other formatters:
stylua ready (lua)
```

**Comment by stevearc** [comment] 2023-12-01 16:13
Oh man...I added a bad commit late at night by messing up my git commands. It should be fixed now. Can you update to latest and see if the issue persists?

**Comment by lgmys** [comment] 2023-12-02 00:23
First thing in the morning;) you are awesome anyway ;D thanks again

**Closed** 2023-12-02 04:08 UTC
Labels: bug

**Comment by lgmys** [comment] 2023-12-02 20:01
it is working as expected now :tada:
